#!/usr/bin/env node
/**
 * Regenerates CATALOG.md from the rules implemented in THIS package.
 *
 * Run after `npm run build` (it imports the compiled registry):
 *   npm run build && npm run build:catalog
 *
 * The full CDK Insights product runs many more rules than are open-sourced here
 * yet — CATALOG.md lists the ones implemented in the open. The complete list
 * lives at https://cdkinsights.dev/rules (and catalog/product-catalog.json).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

let rules;
try {
  ({ rules } = await import(
    pathToFileURL(resolve(root, 'dist', 'index.js')).href
  ));
} catch {
  console.error(
    'Could not import ./dist — run `npm run build` before `npm run build:catalog`.'
  );
  process.exit(1);
}

// How many rules the full product runs (from the reference export), so the
// catalog can honestly state what fraction is open.
let productCount = null;
try {
  const product = JSON.parse(
    readFileSync(resolve(root, 'catalog', 'product-catalog.json'), 'utf8')
  );
  productCount = (product.rules ?? product).length;
} catch {
  // reference data optional
}

const severityOrder = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3 };

const serviceOf = (rule) =>
  rule.metadata.resourceTypes[0]?.split('::')[1] ?? 'Other';

const rulesByService = {};
for (const rule of rules) {
  const service = serviceOf(rule);
  rulesByService[service] ??= [];
  rulesByService[service].push(rule);
}
const services = Object.keys(rulesByService).sort();

const countBySeverity = Object.fromEntries(
  ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'].map((severity) => [
    severity,
    rules.filter((rule) => rule.metadata.severity === severity).length,
  ])
);

const lines = [];
lines.push('# Open Rule Catalog');
lines.push('');
lines.push(
  `**${rules.length} rules** implemented in the open in this package — ` +
    `${countBySeverity.CRITICAL} critical, ${countBySeverity.HIGH} high, ` +
    `${countBySeverity.MEDIUM} medium, ${countBySeverity.LOW} low.`
);
if (productCount) {
  lines.push('');
  lines.push(
    `> This is the open catalog of the rules the [CDK Insights](https://cdkinsights.dev/rules) product runs (${productCount} in the product; the few remaining closed checks need its synth pipeline). [Propose or contribute a rule →](CONTRIBUTING.md)`
  );
}
lines.push('');
lines.push('> Generated by `scripts/build-catalog.mjs` — do not edit by hand.');
lines.push('');

const bySeverityThenId = (first, second) =>
  severityOrder[first.metadata.severity] -
    severityOrder[second.metadata.severity] ||
  first.metadata.ruleId.localeCompare(second.metadata.ruleId);

for (const service of services) {
  lines.push(`## ${service}`);
  lines.push('');
  lines.push('| Rule | Severity | Pillar | Description |');
  lines.push('| --- | --- | --- | --- |');
  for (const rule of rulesByService[service].sort(bySeverityThenId)) {
    const { ruleId, severity, wafPillar, description } = rule.metadata;
    const link = `https://cdkinsights.dev/rules/${ruleId}`;
    lines.push(
      `| [\`${ruleId}\`](${link}) | ${severity} | ${wafPillar} | ${description} |`
    );
  }
  lines.push('');
}

writeFileSync(resolve(root, 'CATALOG.md'), `${lines.join('\n')}\n`);
console.log(`Wrote CATALOG.md (${rules.length} open rules).`);
